# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromuser', models.TextField(max_length=10)),
                ('tousers', models.TextField()),
                ('requires', models.TextField(max_length=500)),
                ('title', models.TextField(max_length=20)),
            ],
        ),
    ]
