# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='tousers',
            field=models.TextField(),
        ),
    ]
